services:
  jupyter:
    build:
      context: .
    ports:
      - 8888:8888
    volumes:
      - jupyter-data:/notebook
    command: start-notebook.py --NotebookApp.token='my-token'

volumes:
  jupyter-data:
    name: jupyter-data